### PR TITLE
bs.json

### PR DESCRIPTION
**Pull request by sabahuddin**
Bosnian translation

### CODE REVIEW

**Comment by timothyylim** [comment]
Hi @sabahuddin , excellent work with all these translations :) 
Just one thing before I merge in, could you rename the files to bs.json. We need to support all platforms including Drupal:

https://api.drupal.org/api/drupal/includes%21iso.inc/function/_locale_get_predefined_list/7.x

**Comment by timothyylim** [comment]
Hey @sabahuddin, I think you might have misunderstood me. I meant that the actual file that you're committing should be renamed to bs.json. Here's an example of one that I've edited:

https://github.com/h5p/h5p-true-false/tree/master/language

Let me know if you would like any help :)

**Comment by sabahuddin** [comment]
Hi @timothyylim, Well, I think I have renamed all my translation files to bs.json. Is it OK with all other files I created yesterday?

**Comment by timothyylim** [comment]
Hi @sabahuddin , most of them are great I think you've just missed out a few:
* Drag Question
* Audio Recorder
* H5P-Video
* Editor Interactive Video
* Falshcards
* Column
* Editor Course Presentation 

And this one, Summary. Almost there! :)

**Comment by sabahuddin** [comment]
Hi @timothyylim,

I changed all except one. I think I need your help with this:

https://github.com/h5p/h5p-moodle-plugin/pull/162

Best regards!

**Comment by timothyylim** [comment]
Nice work @sabahuddin. I'll be more than happy to fix that one as well as the other editor translations when I have a bit more time in the coming days. :)

**Pull request merged**
