### PR TITLE
Adjustment to getting the score

### PR DESCRIPTION
**Pull request by tsivert**
Not all content types have summary. Possible to opt out. Need to handle those as well.

### CODE REVIEW

**Comment by tsivert** [comment]
It would be really really nice if this commit was in the initial release for the H5P.Summary with support for max score. If this doesn't get included the Interactive video will report a wrong score if no summary is provided...

**Comment by tsivert** [comment]
Nice! Thank you!

**Comment by fnoks** [comment]
We are in the middle of releasing this, which changes on the master branch normally is not included. I.e: we are working on the release branch. Therefore, I have merged your latest changes for h5p-summary, h5p-multi-choice and h5p-single-choice-set to the release branch. Are there changes in any other repos I should be aware of?

**Comment by tsivert** [comment]
I see. Old habit... :)

No I don't have any more changes to other repos.

**Comment by fnoks** [comment]
Goody :)

Note: We do want these pull requests on the master branch...

**Comment by tsivert** [comment]
10-4! :)

**Pull request merged**
